apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-example
  template:
    metadata:
      labels:
        app: api-example
    spec:
      containers:
      - name: api-example
        image: acrshgpdev1.azurecr.io/django-api-backend:1
        #imagePullPolicy: Always
        ports:
        - containerPort: 8000
