apiVersion: v1
kind: Service
metadata:
  name: api-example-service
spec:
  selector:
    app: api-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 30800
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-example
  template:
    metadata:
      labels:
        app: api-example
    spec:
      containers:
      - name: api-example
        image: api-example:1.0
        #imagePullPolicy: Always
        ports:
        - containerPort: 8000
