apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-example
  template:
    metadata:
      labels:
        app: api-example
    spec:
      containers:
      - name: api-example
        image: 
        #imagePullPolicy: Always
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: api-example-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: api-example