version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api-example
    volumes:
      - .:/api-example
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
